# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages

stages:
  - clone
  - deploy

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "codefresh-contrib/gitops-certification-examples"
    revision: "main"
    stage: "clone"

  deploy:
    title: Deploying to Staging using Kustomize...
    type: freestyle
    stage: deploy
    working_directory: ${{clone}}/kustomize-app/overlays/production
    arguments:
      image: docker.io/kostiscodefresh/gitops-simple-app:v1.0
      commands:
        - kubectl config use-context docker-desktop
        - kubectl apply -k overlays/production